name: CI — Flag Service

on:
  workflow_dispatch:
  push:
    paths:
      - 'services/flag-service-main/**'
      - 'k8s/**'
      - 'docker-compose.yml'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'services/flag-service-main/**'
      - 'k8s/**'
      - 'docker-compose.yml'
      - '.github/workflows/**'

jobs:
  call:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      service: 'flag'
      context: 'services/flag-service-main'
      dockerfile: 'Dockerfile'
      image_name: 'flag-service'
      language: 'python'
      push: ${{ github.ref == 'refs/heads/main' }}
      tests_command: ''
    secrets:
      ecr_registry: ${{ secrets.ECR_REGISTRY }}
      ecr_repo_prefix: ${{ secrets.ECR_REPOSITORY_PREFIX }}
